### PR TITLE
build: versions plugin added for routine checks of dependency updates, excluding unstable dependencies

### PR DESCRIPTION
**Pull request by morisil**
Usage:

```shell
./gradlew dependencyUpdates
```

### CODE REVIEW

**Comment by hamoid** [comment]
Thank you for this PR! :-) 

Could you please share a few words about it? how, when and why to use these changes?

**Comment by morisil** [comment]
After running  `dependencyUpdates` gradle target, it shows all the dependencies which can be possibly updated in `libs.versions.toml`, based on the latest versions published in maven repositories of the project. Non-stable versions, like rc, alpha, etc., are excluded from the comparison.

**Comment by morisil** [comment]
The plugin is probably less for regular users of the template, more for the maintainers of the `openrndr-template` themselves, to make sure that all the dependencies are updated to the latest versions.

**Comment by hamoid** [comment]
That sounds useful. If it works well we can also add it to openrndr and orx.

**Comment by hamoid** [comment]
A sample result:

```
------------------------------------------------------------
: Project Dependency Updates (report to plain text file)
------------------------------------------------------------

The following dependencies are using the latest milestone version:
 - com.github.ben-manes.versions:com.github.ben-manes.versions.gradle.plugin:0.49.0
 - io.github.microutils:kotlin-logging:3.0.5
 - junit:junit:4.13.2
 - org.beryx.runtime:org.beryx.runtime.gradle.plugin:1.13.0
 - org.jetbrains.kotlin:kotlin-compiler-embeddable:1.8.21
 - org.jetbrains.kotlin:kotlin-klib-commonizer-embeddable:1.8.21
 - org.jetbrains.kotlin:kotlin-script-runtime:1.8.21
 - org.openrndr:openrndr-animatable:0.4.3
 - org.openrndr:openrndr-application:0.4.3
 - org.openrndr:openrndr-dialogs:0.4.3
 - org.openrndr:openrndr-extensions:0.4.3
 - org.openrndr:openrndr-ffmpeg:0.4.3
 - org.openrndr:openrndr-ffmpeg-natives-linux-x64:0.4.3
 - org.openrndr:openrndr-filter:0.4.3
 - org.openrndr:openrndr-gl3:0.4.3
 - org.openrndr:openrndr-gl3-natives-linux-x64:0.4.3
 - org.openrndr:openrndr-openal:0.4.3
 - org.openrndr:openrndr-openal-natives-linux-x64:0.4.3
 - org.openrndr:openrndr-svg:0.4.3
 - org.openrndr.extra:orx-camera:0.4.3
 - org.openrndr.extra:orx-color:0.4.3
 - org.openrndr.extra:orx-compositor:0.4.3
 - org.openrndr.extra:orx-fx:0.4.3
 - org.openrndr.extra:orx-gui:0.4.3
 - org.openrndr.extra:orx-image-fit:0.4.3
 - org.openrndr.extra:orx-no-clear:0.4.3
 - org.openrndr.extra:orx-noise:0.4.3
 - org.openrndr.extra:orx-olive:0.4.3
 - org.openrndr.extra:orx-panel:0.4.3
 - org.openrndr.extra:orx-shade-styles:0.4.3
 - org.openrndr.extra:orx-shapes:0.4.3
 - org.openrndr.extra:orx-video-profiles:0.4.3
 - org.openrndr.extra:orx-view-box:0.4.3
 - org.openrndr.extra.gitarchiver.tomarkdown:org.openrndr.extra.gitarchiver.tomarkdown.gradle.plugin:0.4.3

The following dependencies have later milestone versions:
 - com.fasterxml.jackson.core:jackson-databind [2.14.2 -> 2.15.3]
     https://github.com/FasterXML/jackson
 - com.fasterxml.jackson.dataformat:jackson-dataformat-yaml [2.14.2 -> 2.15.3]
     https://github.com/FasterXML/jackson-dataformats-text
 - com.github.johnrengelman.shadow:com.github.johnrengelman.shadow.gradle.plugin [7.1.2 -> 8.1.1]
 - org.apache.logging.log4j:log4j-core [2.20.0 -> 2.21.1]
     https://logging.apache.org/log4j/2.x/
 - org.apache.logging.log4j:log4j-slf4j2-impl [2.20.0 -> 2.21.1]
     https://logging.apache.org/log4j/2.x/
 - org.jetbrains.kotlin:kotlin-stdlib-jdk8 [1.8.21 -> 1.9.20]
     https://kotlinlang.org/
 - org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin [1.8.21 -> 1.9.20]
     https://kotlinlang.org/
 - org.jetbrains.kotlinx:kotlinx-coroutines-core [1.7.0 -> 1.7.3]
     https://github.com/Kotlin/kotlinx.coroutines
 - org.slf4j:slf4j-api [2.0.7 -> 2.0.9]
     http://www.slf4j.org

Gradle current updates:
 - Gradle: [8.3 -> 8.4]
```

**Pull request merged**
